config/routes.rb
Rails.application.routes.draw do
  root "authors#index"
  resources :books
  resources :authors do
    member do
      get :books
      delete :delete_image_attachment
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_one_attached :profile_picture
  has_many :books, dependent: :destroy

  validates :name, :address, presence: true
  validates :profile_picture, content_type: { in: 'image/png', message: 'Profile picture must be in PNG format' }, size: { less_than: 1.megabytes , message: 'Profile picture should be less than 1 MB!' }, aspect_ratio: :square
end

app/models/book.rb
class Book < ApplicationRecord
  has_many_attached :cover_photos
  belongs_to :author

  validates :name, presence: true
  validates :cover_photos, content_type: { in: 'image/png', message: 'Cover photos must be in PNG format' }, size: { less_than: 1.megabytes , message: 'Cover photos should be less than 1 MB!' }, aspect_ratio: :square
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include Pagy::Backend
  Pagy::DEFAULT[:items] = 5
  before_action :set_author, only: %i[ show edit update destroy delete_picture]

  # GET /authors or /authors.json
  def index
    @pagy, @authors = pagy(Author.all)
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to root_url, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @image = ActiveStorage::Blob.find_signed(params[:id])
    @image.attachments.first.purge_later
    
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Profile picture successfully removed..." }
      format.json { head :no_content }
    end
  end

  def books
    @pagy, @books = pagy(Book.where(author_id: params[:id]))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :address, :profile_picture)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author_id, cover_photos: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
    include Pagy::Frontend
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <div class="card me-2">
    <div class="card-header">
        <p><%= link_to author.name, author %><br/>
        <%= author.address %></p>
        <p><%= link_to "Show books", books_author_path(author.id) %></p>
    </div>
    <% if author.profile_picture.attached? %>
      <%= image_tag (author.profile_picture.representation(resize_to_limit: [150, 150])), class: "card-img-top" if author.profile_picture.attached? %>
      <div class="card-body">
        <%= link_to "View Pic", rails_blob_path(author.profile_picture, disposition: "preview"), class: "card-link" %><br/>
        <%= button_to "Delete Pic", delete_image_attachment_author_path(author.profile_picture.signed_id), method: :delete, class: "card-link" %><br/>
        <%= link_to "Download Pic", rails_blob_path(author.profile_picture, disposition: "attachment"), class: "card-link" %>
      </div>
    <% else %>
      <div class="card-body">
        <p>No profile_picture<br/>attached</p>
      </div>
    <% end %> 
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.file_field :profile_picture, accept: ".png" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/books.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<% if @books.empty? %>
  <p>No books...</p>
<% else %>
  <div>
    <div class="d-flex flex-row align-items-start align-self-start" id="books">
      <% @books.each do |book| %>
        <div class="card me-2">
        <div class="card-header">
            <p><%= link_to book.name, book %></p>
        </div>
        <% if book.cover_photos.attached? %>
          <% (book.cover_photos).each do |image| %>
            <%= image_tag (image.representation(resize_to_limit: [150, 150])), class: "card-img-top" if book.cover_photos.attached? %>
            <div class="card-body">
              <%= link_to "View", rails_blob_path(image, disposition: "preview"), class: "card-link" %>
            </div>
          <% end %>
        <% else %>
          <div class="card-body">
            <p>No cover_photos<br/>attached</p>
          </div>
        <% end %>
        <%= link_to "Show this book", book, class: "card-body card-text" %> 
        </div>
      <% end %>
    </div>
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

<%= link_to "Back to Home", root_path %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div>
  <span>Add new</span>
  <div>
    <%= link_to "Author", new_author_path %><br/>
    <%= link_to "Book", new_book_path %>
  </div>
</div>

<div>
  <div class="d-flex flex-row align-items-start align-self-start" id="authors">
    <% @authors.each do |author| %>
      <%= render author %>
    <% end %>
  </div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to Authors", authors_path %><br/>
  <%= link_to "Back to Home", root_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex flex-row align-items-start align-self-start">
  <%= render @author %>
</div>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <div class="card me-2">
    <div class="card-header">
        <p><%= link_to book.name, book %></p>
    </div>
    <% if book.cover_photos.attached? %>
      <% (book.cover_photos).each do |image| %>
        <%= image_tag (image.representation(resize_to_limit: [150, 150])), class: "card-img-top" if book.cover_photos.attached? %>
        <div class="card-body">
          <%= link_to "View Pic", rails_blob_path(image, disposition: "preview"), class: "card-link" %>
        </div>
      <% end %>
    <% else %>
      <div class="card-body">
        <p>No cover_photos<br/>attached</p>
      </div>
    <% end %>
    <%= link_to "Show this book", book, class: "card-body card-text" %> 
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cover_photos, style: "display: block" %>
    <%= form.file_field :cover_photos, multiple: true, accept: ".png"%>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.collection_select :author_id, Author.order(:name),:id,:name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div class="d-flex flex-row align-items-start align-self-start" id="books">
  <% @books.each do |book| %>
    <%= render book %>
  <% end %>
</div>

<%= link_to "New book", new_book_path %><br/>
<%= link_to "Back to Home", root_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to Books", books_path %><br/>
  <%= link_to "Back to Home", root_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex flex-row align-items-start align-self-start">
  <%= render @book %>
</div>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>
<br/>
<%= link_to "Back to Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>